FROM python:3.9-alpine
ADD generator.py .
RUN pip install faker kafka-python
ENV KAFKA_TOPIC=$KAFKA_TOPIC
ENV KAFKA_SERVER=$KAFKA_SERVER
ENV KAFKA_PORT=$KAFKA_PORT
CMD python ./generator.py ${KAFKA_SERVER} ${KAFKA_PORT} ${KAFKA_TOPIC} 
