---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3-2-ubi8
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.5.3-2-ubi8
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  generator:
    image: web-traffic-generator 
    container_name: base_generator 
    depends_on:
      - kafka
    environment:
      - KAFKA_TOPIC=base_data
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
  
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    depends_on:
      - kafka
    volumes:
      - ./clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

