---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3-2-ubi8
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.5.3-2-ubi8
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  generator:
    image: generator/internet_generator:2.0
    container_name: base_generator 
    depends_on:
      - kafka
    environment:
      - KAFKA_TOPIC=rawData
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
      - COOKIE_NUMBER=1000
      - DOMAIN=example.com
      - SLEEP_TIME=0.1
      - ROTATION_PROB=0.0033
  
  preprocessing:
    image: preprocessing:2.0 
    container_name: preprocessing 
    depends_on:
      - kafka
    environment:
      - IN_KAFKA_TOPIC=rawData
      - OUT_KAFKA_TOPIC=baseData
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
  
  processing:
    image: processing:2.0 
    container_name: processing 
    depends_on:
      - kafka
    environment:
      - IN_KAFKA_TOPIC=baseData
      - OUT_KAFKA_TOPIC_DECO=eventsDecorated
      - OUT_KAFKA_TOPIC_SESSION=sessionData
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
      - USER_SESSION_MAX_GAP_MINUTES=5
  
  
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    depends_on:
      - kafka
    environment:
      CLICKHOUSE_USER: clickuser
      CLICKHOUSE_PASSWORD: clickpass
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ../clickhouse/2.0/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  
  metabase:
    image: metabase-clickhouse-driver
    container_name: metabase
    depends_on: 
    - clickhouse
    ports:
    - 3000:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
    - ../metabase/2.0/data:/metabase-data
